PackageIdentifier: WallTUI.WallTUI
PackageVersion: 1.1.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: walltui.exe
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/iztlinxy/walltui/releases/download/v1.1.0/walltui-x86_64-pc-windows-msvc.zip
    InstallerSha256: 670F016471844138CA22482550097E98B5EE03B0FD311A0A232A37B3A0B6DC0D
ManifestType: installer
ManifestVersion: 1.6.0
